name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-14
    timeout-minutes: 30
    env:
      SECRET_URL: "${{ secrets.SECRET_URL }}"
      SECRET_KEY: "${{ secrets.SECRET_KEY }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.fastlane
          key: session-${{ github.run_id }}
          restore-keys: |
            session

      - name: Debug Info
        run: |
          ls -la
          which python3
          python3 --version

      - name: Install Dependencies
        run: |
          python3 -m pip install -r requirements.txt || true

      - name: Run Sign Script
        run: |
          python3 sign.py
